# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(382, 510)
        self.go_to_private_office = QtWidgets.QPushButton(parent=Form)
        self.go_to_private_office.setGeometry(QtCore.QRect(100, 80, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.go_to_private_office.setFont(font)
        self.go_to_private_office.setObjectName("go_to_private_office")
        self.go_to_create_tests = QtWidgets.QPushButton(parent=Form)
        self.go_to_create_tests.setGeometry(QtCore.QRect(100, 180, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.go_to_create_tests.setFont(font)
        self.go_to_create_tests.setMouseTracking(False)
        self.go_to_create_tests.setObjectName("go_to_create_tests")
        self.go_to_catalog = QtWidgets.QPushButton(parent=Form)
        self.go_to_catalog.setGeometry(QtCore.QRect(100, 280, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.go_to_catalog.setFont(font)
        self.go_to_catalog.setMouseTracking(False)
        self.go_to_catalog.setObjectName("go_to_catalog")
        self.logoutbtn = QtWidgets.QPushButton(parent=Form)
        self.logoutbtn.setGeometry(QtCore.QRect(10, 470, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logoutbtn.setFont(font)
        self.logoutbtn.setObjectName("logoutbtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.go_to_private_office.setText(_translate("Form", "Личный кабинет"))
        self.go_to_create_tests.setText(_translate("Form", "Переход к\n"
" созданию тестов"))
        self.go_to_catalog.setText(_translate("Form", "Переход к\n"
" каталогу тестов"))
        self.logoutbtn.setText(_translate("Form", "Выйти из аккаунта"))
