# Form implementation generated from reading ui file 'PrivateOffice.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1048, 510)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.username = QtWidgets.QLabel(parent=Form)
        self.username.setGeometry(QtCore.QRect(170, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setText("")
        self.username.setObjectName("username")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(560, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.passedtests = QtWidgets.QTableWidget(parent=Form)
        self.passedtests.setGeometry(QtCore.QRect(10, 90, 481, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.passedtests.setFont(font)
        self.passedtests.setObjectName("passedtests")
        self.passedtests.setColumnCount(0)
        self.passedtests.setRowCount(0)
        self.createdtests = QtWidgets.QTableWidget(parent=Form)
        self.createdtests.setGeometry(QtCore.QRect(560, 90, 481, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.createdtests.setFont(font)
        self.createdtests.setObjectName("createdtests")
        self.createdtests.setColumnCount(0)
        self.createdtests.setRowCount(0)
        self.backbtn = QtWidgets.QPushButton(parent=Form)
        self.backbtn.setGeometry(QtCore.QRect(940, 470, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backbtn.setFont(font)
        self.backbtn.setObjectName("backbtn")
        self.logoutbtn = QtWidgets.QPushButton(parent=Form)
        self.logoutbtn.setGeometry(QtCore.QRect(10, 470, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logoutbtn.setFont(font)
        self.logoutbtn.setObjectName("logoutbtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя пользователя:"))
        self.label_2.setText(_translate("Form", "Решеные тесты:"))
        self.label_3.setText(_translate("Form", "Созданые тесты:"))
        self.backbtn.setText(_translate("Form", "Назад"))
        self.logoutbtn.setText(_translate("Form", "Выйти из аккаунта"))
