# Form implementation generated from reading ui file 'StatisticFirst.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(348, 379)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.right = QtWidgets.QLabel(parent=Form)
        self.right.setGeometry(QtCore.QRect(130, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.right.setFont(font)
        self.right.setText("")
        self.right.setObjectName("right")
        self.wrong = QtWidgets.QLabel(parent=Form)
        self.wrong.setGeometry(QtCore.QRect(150, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wrong.setFont(font)
        self.wrong.setText("")
        self.wrong.setObjectName("wrong")
        self.wrongNumbers = QtWidgets.QLabel(parent=Form)
        self.wrongNumbers.setGeometry(QtCore.QRect(110, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wrongNumbers.setFont(font)
        self.wrongNumbers.setText("")
        self.wrongNumbers.setObjectName("wrongNumbers")
        self.backbtn = QtWidgets.QPushButton(parent=Form)
        self.backbtn.setGeometry(QtCore.QRect(80, 340, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backbtn.setFont(font)
        self.backbtn.setObjectName("backbtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Статистика:"))
        self.label_2.setText(_translate("Form", "Решено верно:"))
        self.label_3.setText(_translate("Form", "Решено неверно:"))
        self.label_4.setText(_translate("Form", "Задания в которых допущена ошибка:"))
        self.backbtn.setText(_translate("Form", "Вернуться в меню"))
